# Generated by Django 5.0.3 on 2024-04-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_contact_user_alter_contact_name_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='campus',
            field=models.CharField(default='保密', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='qq',
            field=models.CharField(default='保密', max_length=15),
        ),
        migrations.AddField(
            model_name='contact',
            name='wechat',
            field=models.CharField(default='保密', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='保密', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='保密', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='保密', max_length=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
